/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLogin: typeof import('./src/components/AdminLogin.vue')['default']
    BikeSearch: typeof import('./src/components/search/BikeSearch.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MapContainer: typeof import('./src/components/MapContainer.vue')['default']
    MapPanel: typeof import('./src/components/MapPanel.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NoparkingSearch: typeof import('./src/components/search/NoparkingSearch.vue')['default']
    NoParkingSearch: typeof import('./src/components/search/NoParkingSearch.vue')['default']
    RecordSearch: typeof import('./src/components/search/RecordSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchAppearence: typeof import('./src/components/SwitchAppearence.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UserSearch: typeof import('./src/components/search/UserSearch.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
